### ISSUE TITLE
Application architecture

### ISSUE THREAD

**Issue by zachwaite** [javascriptFundamentalists/stock-data-visualizer#4]
### General technical considerations for this app:

- [x] How to get data from API (e.g. fetch vs axios, async / await vs promise resolution)
- [x] Is navigation necessary? (menus, routing)
- [x] Is templating necessary?
- [x] Can we use modularize using components?

**Comment by zachwaite** [comment]
I added lit-html for templating. It is literally html, so the learning curve is insignificant. I recommend axios for API interaction. Holding off on routing for now. I'd like to establish some kind of component pattern, but not sure the best technique yet.

**Comment by zachwaite** [comment]
I have a simple component pattern in zach-dev branch.  Will add documentation later

**Comment by vyaskruti89** [comment]
i like to have navigation bar

**Comment by vyaskruti89** [comment]
i am ok with axios for API interaction.

**Comment by zachwaite** [comment]
Using axios, async / await where applicable or native promise resolution. Kruti is looking at menus

**Comment by zachwaite** [comment]
Closing this as done. Navigation issue is covered in #9
