### ISSUE TITLE
Decide on git branches vs. pull requests

### ISSUE THREAD

**Issue by zachwaite** [javascriptFundamentalists/stock-data-visualizer#7]
**branches:** each person has a branch e.g. dev-zach, dev-kruti, dev-brian and we push there, then merge into master as we approve work.

**pull requests:** each person forks this repo and works like we do in class; to get the latest work: `git pull upstream master`, and to commit our work, `git push origin master` + a pull request to the upstream (this repo)

I'd prefer to use pull requests, but branches is fine too

**Comment by vyaskruti89** [comment]
pull requests is fine with me. we can discuss the ideas and stuff over the slack so i think pull request is better option.

**Comment by zachwaite** [comment]
PR's it is
